### ISSUE TITLE
No module named 'quark'

### ISSUE THREAD

**Issue by onemoreflag** [quark-engine/quark-rule-generate#1]
Traceback (most recent call last):
  File "start.py", line 14, in <module>
    from model.android_sample_model import AndroidSampleModel
  File "\quark-rule-generate\model\android_sample_model.py", line 2, in <module>
    from quark.Objects.quark import Quark
ModuleNotFoundError: No module named 'quark'

Although I did all the steps
$ git clone https://github.com/quark-engine/quark-rule-generate.git; cd quark-rule-generate/
$ pipenv install --skip-lock
$ pipenv shell
$ git submodule init
$ git submodule update --remote; cd quark-engine/
$ python setup.py install; cd ..

**Comment by pulorsok** [comment]
Hi @onemoreflag ,
This mean Quark-Engine is not installed well in your environment.

Since we haven't update our new version of Quark-Engine on PyPl, The install script will manually clone Quark-Engine and switch to the specific commit then setup.
So make sure the Quark-Engine has cloned completely and the current commit is at `709b018`
then make sure it setup successfully into the `(quark-rule-generate) pipenv`.

If all the steps are goes well and still have the same problem, please let me know :D
